model:
  base_learning_rate: 5.0e-08 #1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 32
    channels: 4
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 512
        out_channels: 512
        model_channels: 256
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage
    cond_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1200
    num_workers: 16
    wrap: false
    train:
      target: ldm.data.feature.SICAPTrain
      params:
        root_dir: /data114_2/shaozc/unitopath-public/512/pt_files/
    validation:
      target: ldm.data.feature.SICAPValidation
      params:
        root_dir: /data114_2/shaozc/unitopath-public/512/pt_files/

lightning:

  trainer:
    benchmark: True
    gpus: 0,1,2